### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by BenHilling** [OpenToontownTools/OpenLevelEditor#33]
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-py39-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-py39-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\ttle.py", line 258, in <module>
    ToontownLevelEditor().run()
  File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\ttle.py", line 146, in __init__
    self.le = LevelEditor.LevelEditor()
  File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelEditor.py", line 103, in __init__
    self.styleManager = LevelStyleManager(NEIGHBORHOODS, NEIGHBORHOOD_CODES)
  File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 21, in __init__
    self.createWallStyleAttributes()
  File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 169, in createWallStyleAttributes
    self.createWallStyleMenu(neighborhood, attribute.getDict()))
  File "E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 252, in createWallStyleMenu
    bounds = node.getBounds()
AssertionError: !is_empty() at line 538 of panda/src/pgraph/nodePath.cxx

E:\Downloads\OpenLevelEditor-master\OpenLevelEditor-master>pause

**Comment by NathanX-S** [comment]
this provides no context as to how the.. crash? occured? and is literally just a traceback copy pasted

**Comment by BenHilling** [comment]
Its not a crash it just happened when I loaded it

**Comment by NathanX-S** [comment]
loaded what? the program?

**Comment by drewc5131** [comment]
Please follow the template when creating an issue. I am going to close this because theres no context.
