### ISSUE TITLE
Suitpoint isssues

### ISSUE THREAD

**Issue by GabeTheReallyHappyDog48** [OpenToontownTools/OpenLevelEditor#36]
## Describe the bug
I Place down a suitpoint and when I click on the point I place down I get this 

## System Info

 - OS: 

 - Command Line: 

 - Source of resources

 - Panda Version: `
`
## Checklist
- [x] Did you read the entirety of the `[readme](https://github.com/OpenToontownTools/OpenLevelEditor/blob/master/README.md)?`
- [x] Did you check for duplicate issues?

`
C:\Users\Gabep\Downloads\OpenLevelEditor>"C:/Panda3D-1.11.0-Py39-x64/python/python.exe" -m pip install -r requirements.txt
Requirement already satisfied: aiohttp in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from -r requirements.txt (line 1)) (3.7.2)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (3.7.4.3)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (5.0.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (20.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.6.2)
Requirement already satisfied: idna>=2.0 in c:\panda3d-1.11.0-py39-x64\python\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 1)) (2.10)
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Panda3D-1.11.0-Py39-x64\python\python.exe -m pip install --upgrade pip' command.

C:\Users\Gabep\Downloads\OpenLevelEditor>"C:/Panda3D-1.11.0-Py39-x64/python/python.exe" -m ttle --hoods DL
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
Registered shader render:black_and_white
Registered shader dna:anim_prop
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_4/dna/storage.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_5/dna/storage_town.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_8/dna/storage_DL.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_8/dna/storage_DL_sz.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_8/dna/storage_DL_town.dna
Loading baseline styles from: donalds_dreamland/baseline_styles.txt
Loading wall styles from: donalds_dreamland/wall_styles.txt
Loading building styles from: donalds_dreamland/building_styles.txt
Loading Color Palettes from: donalds_dreamland/colors.txt
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/leveleditor/New Street.dna
Finished Load:  C:/Users/Gabep/Downloads/OpenLevelEditor/leveleditor/New Street.dna
Suit point: LPoint3f(667.7, 57.6788, 0)
placeSuitPoint:  store_suit_point [ 0, STREET_POINT, 667.7 57.6788 0 ]

Found suit point! store_suit_point [ 0, STREET_POINT, 667.7 57.6788 0 ]

Found suit point! store_suit_point [ 0, STREET_POINT, 667.7 57.6788 0 ]

Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.11.0-Py39-x64\direct\directtools\DirectSession.py", line 568, in inputHandler
    messenger.send('DIRECT-mouse1Up')
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.11.0-Py39-x64\direct\directtools\DirectManipulation.py", line 342, in manipulationStop
    self.manipulateObjectCleanup()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\directtools\DirectManipulation.py", line 370, in manipulateObjectCleanup
    messenger.send('DIRECT_manipulateObjectCleanup',
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Gabep\Downloads\OpenLevelEditor\toontown\leveleditor\LevelEditor.py", line 1161, in updateSelectedPose
    for edge in self.point2edgeDict[pointOrCell]:
KeyError: <0, STREET_POINT, 667.7 57.6788 0>
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gabep\Downloads\OpenLevelEditor\ttle.py", line 258, in <module>
    ToontownLevelEditor().run()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\ShowBase.py", line 3316, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\task\Task.py", line 535, in run
    self.step()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\task\Task.py", line 489, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.11.0-Py39-x64\direct\directtools\DirectSession.py", line 568, in inputHandler
    messenger.send('DIRECT-mouse1Up')
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.11.0-Py39-x64\direct\directtools\DirectManipulation.py", line 342, in manipulationStop
    self.manipulateObjectCleanup()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\directtools\DirectManipulation.py", line 370, in manipulateObjectCleanup
    messenger.send('DIRECT_manipulateObjectCleanup',
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\Gabep\Downloads\OpenLevelEditor\toontown\leveleditor\LevelEditor.py", line 1161, in updateSelectedPose
    for edge in self.point2edgeDict[pointOrCell]:
KeyError: <0, STREET_POINT, 667.7 57.6788 0>

C:\Users\Gabep\Downloads\OpenLevelEditor>pause
Press any key to continue . . .

C:\Users\Gabep\Downloads\OpenLevelEditor>goto top

C:\Users\Gabep\Downloads\OpenLevelEditor>"C:/Panda3D-1.11.0-Py39-x64/python/python.exe" -m ttle --hoods DL
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
Registered shader render:black_and_white
Registered shader dna:anim_prop
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_4/dna/storage.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_5/dna/storage_town.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_8/dna/storage_DL.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_8/dna/storage_DL_sz.dna
:dna: Reading /c/Users/Gabep/Downloads/OpenLevelEditor/phase_8/dna/storage_DL_town.dna
Loading baseline styles from: donalds_dreamland/baseline_styles.txt
Loading wall styles from: donalds_dreamland/wall_styles.txt
Loading building styles from: donalds_dreamland/building_styles.txt
Loading Color Palettes from: donalds_dreamland/colors.txt
`

**Comment by drewc5131** [comment]
Make sure you have a visgroup selected when you place the suit point.  Selecting one outside will crash. Known issue. Also a repeat of #31. **Also you still didnt fill out the form like i asked 3 times.**

**Comment by drewc5131** [comment]
Dont click on a suit point thats not connected to anything. Make sure you have a visgroup set as a reparent target. and that is NOT how you upload files...
