### ISSUE TITLE
Crash changing windows

### ISSUE THREAD

**Issue by hunterboppen** [OpenToontownTools/OpenLevelEditor#40]
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hunte\Downloads\OpenLevelEditor-master (1)\OpenLevelEditor-master\ttle.py", line 261, in <module>
    ToontownLevelEditor().run()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\ShowBase.py", line 3316, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\task\Task.py", line 535, in run
    self.step()
  File "C:\Panda3D-1.11.0-Py39-x64\direct\task\Task.py", line 489, in step
    self.mgr.poll()
  File "C:\Users\hunte\Downloads\OpenLevelEditor-master (1)\OpenLevelEditor-master\toontown\leveleditor\PieMenu.py", line 91, in pieMenuTask
    self.performAction(self.initialState)
  File "C:\Users\hunte\Downloads\OpenLevelEditor-master (1)\OpenLevelEditor-master\toontown\leveleditor\PieMenu.py", line 41, in performAction
    self.action(value)
  File "C:\Users\hunte\Downloads\OpenLevelEditor-master (1)\OpenLevelEditor-master\toontown\leveleditor\LevelStyleManager.py", line 969, in setCurrent
    messenger.send('select_' + self.name, [self._current])
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 336, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-Py39-x64\direct\showbase\Messenger.py", line 421, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Users\hunte\Downloads\OpenLevelEditor-master (1)\OpenLevelEditor-master\toontown\leveleditor\LevelEditor.py", line 2068, in setWindowCount
    self.DNATarget = self.createWindows()
  File "C:\Users\hunte\Downloads\OpenLevelEditor-master (1)\OpenLevelEditor-master\toontown\leveleditor\LevelEditor.py", line 1707, in createWindows
    newDNAWindows.setWindowCount(self.getCurrent('window_count'))
TypeError: arguments do not match any function overload

**Comment by drewc5131** [comment]
Please follow proper report format.
