### ISSUE TITLE
Loading OZ hood crashes

### ISSUE THREAD

**Issue by TheNotZen364** [OpenToontownTools/OpenLevelEditor#44]
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\ttle.py", line 263, in <module>
    ToontownLevelEditor().run()
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\ttle.py", line 150, in __init__
    self.le = LevelEditor.LevelEditor()
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelEditor.py", line 109, in __init__
    self.styleManager = LevelStyleManager(NEIGHBORHOODS, NEIGHBORHOOD_CODES)
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelStyleManager.py", line 21, in __init__
    self.createWallStyleAttributes()
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelStyleManager.py", line 169, in createWallStyleAttributes
    self.createWallStyleMenu(neighborhood, attribute.getDict()))
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelStyleManager.py", line 252, in createWallStyleMenu
    bounds = node.getBounds()
AssertionError: !is_empty() at line 538 of panda/src/pgraph/nodePath.cxx

(please ignore the train simulator directory)

**Comment by BenHilling** [comment]
Bit more info, its trying to find an OZ Town dna file

**Comment by BenHilling** [comment]
after removing the oz town from the hood json

I now get this

:dna: Reading /e/Train Simulator/OpenLevelEditor-1.1.16/OpenLevelEditor-1.1.16/phase_4/dna/storage.dna
:dna: Reading /e/Train Simulator/OpenLevelEditor-1.1.16/OpenLevelEditor-1.1.16/phase_5/dna/storage_town.dna
:dna: Reading /e/Train Simulator/OpenLevelEditor-1.1.16/OpenLevelEditor-1.1.16/phase_6/dna/storage_OZ.dna
:dna: Reading /e/Train Simulator/OpenLevelEditor-1.1.16/OpenLevelEditor-1.1.16/phase_6/dna/storage_OZ_sz.dna
Loading baseline styles from: outdoor_zone/baseline_styles.txt
Loading wall styles from: outdoor_zone/wall_styles.txt
Assertion failed: !is_empty() at line 538 of panda/src/pgraph/nodePath.cxx
Assertion failed: !is_empty() at line 1243 of panda/src/pgraph/nodePath.cxx
Assertion failed: !is_empty() at line 1964 of panda/src/pgraph/nodePath.cxx
Assertion failed: !is_empty() at line 228 of P:\P3D\p3_py39\built_x64\include\nodePath.I
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-Py39-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\ttle.py", line 258, in <module>
    ToontownLevelEditor().run()
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\ttle.py", line 146, in __init__
    self.le = LevelEditor.LevelEditor()
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelEditor.py", line 105, in __init__
    self.styleManager = LevelStyleManager(NEIGHBORHOODS, NEIGHBORHOOD_CODES)
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelStyleManager.py", line 21, in __init__
    self.createWallStyleAttributes()
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelStyleManager.py", line 169, in createWallStyleAttributes
    self.createWallStyleMenu(neighborhood, attribute.getDict()))
  File "E:\Train Simulator\OpenLevelEditor-1.1.16\OpenLevelEditor-1.1.16\toontown\leveleditor\LevelStyleManager.py", line 252, in createWallStyleMenu
    bounds = node.getBounds()
AssertionError: !is_empty() at line 538 of panda/src/pgraph/nodePath.cxx
